# -*- coding: utf-8 -*-
"""Digit Recognizer

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WMjtERUh1HUCQ95GGeNdaVkm-yedSs24
"""

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
import matplotlib.pyplot as plt

def download_training_dataset(batch_size):
  transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5,), (0.5,))])
  train_set = torchvision.datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=True, transform=transform)
  train_loader = torch.utils.data.DataLoader(train_set, batch_size=batch_size, shuffle=True)
  return train_loader
def download_testing_dataset(batch_size):
  transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5,), (0.5,))])
  test_set = torchvision.datasets.MNIST('~/.pytorch/MNIST_data/', download=True, train=False, transform=transform)
  test_loader = torch.utils.data.DataLoader(test_set, batch_size=batch_size, shuffle=True)
  return test_loader

class CNN1(nn.Module):
  #BASE MODEL FOR COMPARISON
  def __init__(self,num_classes=10):
    super(CNN1,self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=1,out_channels=16,kernel_size=5,stride=1,padding=2),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #14
    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=16,out_channels=32,kernel_size=5,stride=1,padding=2),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #7
    self.layer3 = nn.Sequential(
        nn.Conv2d(in_channels=32,out_channels=64,kernel_size=5,stride=1,padding=2),
        nn.ReLU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #3
    self.fc1 = nn.Linear(in_features = 3*3*64,out_features=num_classes)

  def forward(self,x):
    x = self.layer1(x)
    x = self.layer2(x)
    x = self.layer3(x)
    x = x.reshape(x.size(0),-1)
    x = self.fc1(x)
    return x
class CNN2(nn.Module):
  #GELU variation
  def __init__(self,num_classes=10):
    super(CNN2,self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=1,out_channels=16,kernel_size=5,stride=1,padding=2),
        nn.GELU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #14
    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=16,out_channels=32,kernel_size=5,stride=1,padding=2),
        nn.GELU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #7
    self.layer3 = nn.Sequential(
        nn.Conv2d(in_channels=32,out_channels=64,kernel_size=5,stride=1,padding=2),
        nn.GELU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #3
    self.fc1 = nn.Linear(in_features = 3*3*64,out_features=num_classes)

  def forward(self,x):
    x = self.layer1(x)
    x = self.layer2(x)
    x = self.layer3(x)
    x = x.reshape(x.size(0),-1)
    x = self.fc1(x)
    return x
class CNN3(nn.Module):
  #ELU variation
  def __init__(self,num_classes=10):
    super(CNN3,self).__init__()
    self.layer1 = nn.Sequential(
        nn.Conv2d(in_channels=1,out_channels=16,kernel_size=5,stride=1,padding=2),
        nn.ELU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #14
    self.layer2 = nn.Sequential(
        nn.Conv2d(in_channels=16,out_channels=32,kernel_size=5,stride=1,padding=2),
        nn.ELU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #7
    self.layer3 = nn.Sequential(
        nn.Conv2d(in_channels=32,out_channels=64,kernel_size=5,stride=1,padding=2),
        nn.ELU(),
        nn.MaxPool2d(kernel_size=2,stride=2)
    ) #3
    self.fc1 = nn.Linear(in_features = 3*3*64,out_features=num_classes)

  def forward(self,x):
    x = self.layer1(x)
    x = self.layer2(x)
    x = self.layer3(x)
    x = x.reshape(x.size(0),-1)
    x = self.fc1(x)
    return x

def plotter(batch_numbers,accuracies,title,x_label,y_label):
  plt.plot(batch_numbers,accuracies)
  plt.title(title)
  plt.xlabel(x_label)
  plt.ylabel(y_label)
  plt.grid(True, linestyle=':', alpha=0.6)
  plt.show()
def train_model(model,train_loader,num_epochs,learning_rate,device):
  model.train()
  criterion = nn.CrossEntropyLoss()
  optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)
  batch_numbers = []
  accuracies = []
  title = 'Accuracy vs Batch Number'
  x_label = 'Batch Number'
  y_label = 'Accuracy'
  epoch_number = 0
  for i in range(num_epochs):
    for j, item in enumerate(train_loader):
      images,labels = item
      images = images.to(device)
      labels = labels.to(device)

      outputs = model(images)
      loss = criterion(outputs,labels)

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

      if epoch_number % 100 == 0:
        guesses = torch.max(outputs,dim=1)
        accuracies.append((guesses[1] == labels).sum().item() / len(labels) * 100)
        batch_numbers.append(epoch_number)
      epoch_number += 1
  plotter(batch_numbers,accuracies,title,x_label,y_label)

def train_model_hinge(model,train_loader,num_epochs,learning_rate,device):
  model.train()
  criterion = nn.MultiMarginLoss()
  optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)
  batch_numbers = []
  accuracies = []
  title = 'Accuracy vs Batch Number'
  x_label = 'Batch Number'
  y_label = 'Accuracy'
  epoch_number = 0
  for i in range(num_epochs):
    for j, item in enumerate(train_loader):
      images,labels = item
      images = images.to(device)
      labels = labels.to(device)

      outputs = model(images)
      loss = criterion(outputs,labels)

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()
      if epoch_number % 100 == 0:
        guesses = torch.max(outputs,dim=1)
        accuracies.append((guesses[1] == labels).sum().item() / len(labels) * 100)
        batch_numbers.append(epoch_number)
      epoch_number += 1
  plotter(batch_numbers,accuracies,title,x_label,y_label)

def test_model(model,test_loader,device):
  model.eval()
  with torch.no_grad():
    total_samples = 0
    correct_samples = 0
    for i, item in enumerate(test_loader):
      images,labels = item
      images = images.to(device)
      labels = labels.to(device)
      outputs = model(images)
      values, estimates = torch.max(outputs,dim=1)
      total_samples += outputs.size(0)
      correct_samples += (labels == estimates).sum().item()
    return correct_samples * 100 / total_samples

def train_run_test_base():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN1().to(device)
  train_model(model,train_loader,10,0.01,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN1 (ReLU)')
  print(f'Loss: Cross Entropy')
  print(f'LR: 0.01')
  print(f'Accuracy: {accuracy}%')
def train_run_test_GELU():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN2().to(device)
  train_model(model,train_loader,10,0.01,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN2 (GELU)')
  print(f'Loss: Cross Entropy')
  print(f'LR: 0.01')
  print(f'Accuracy: {accuracy}%')
def train_run_test_ELU():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN3().to(device)
  train_model(model,train_loader,10,0.01,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN3 (ELU)')
  print(f'Loss: Cross Entropy')
  print(f'LR: 0.01')
  print(f'Accuracy: {accuracy}%')
def train_run_test_base_hinge():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN1().to(device)
  train_model_hinge(model,train_loader,10,0.01,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN1 (ReLU)')
  print(f'Loss: MultiMargin')
  print(f'LR: 0.01')
  print(f'Accuracy: {accuracy}%')
def train_run_test_GELU_hinge():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN2().to(device)
  train_model_hinge(model,train_loader,10,0.01,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN2 (GELU)')
  print(f'Loss: MultiMargin')
  print(f'LR: 0.01')
  print(f'Accuracy: {accuracy}%')
def train_run_test_ELU_hinge():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN3().to(device)
  train_model_hinge(model,train_loader,10,0.01,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN3 (ELU)')
  print(f'Loss: MultiMargin')
  print(f'LR: 0.01')
  print(f'Accuracy: {accuracy}%')

def train_run_test_base_1():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN1().to(device)
  train_model(model,train_loader,10,0.1,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN1 (ReLU)')
  print(f'Loss: Cross Entropy')
  print(f'LR: 0.1')
  print(f'Accuracy: {accuracy}%')
def train_run_test_GELU_1():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN2().to(device)
  train_model(model,train_loader,10,0.1,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN2 (GELU)')
  print(f'Loss: Cross Entropy')
  print(f'LR: 0.1')
  print(f'Accuracy: {accuracy}%')
def train_run_test_ELU_1():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN3().to(device)
  train_model(model,train_loader,10,0.1,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN3 (ELU)')
  print(f'Loss: Cross Entropy')
  print(f'LR: 0.1')
  print(f'Accuracy: {accuracy}%')
def train_run_test_base_hinge_1():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN1().to(device)
  train_model_hinge(model,train_loader,10,0.1,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN1 (ReLU)')
  print(f'Loss: MultiMargin')
  print(f'LR: 0.1')
  print(f'Accuracy: {accuracy}%')
def train_run_test_GELU_hinge_1():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN2().to(device)
  train_model_hinge(model,train_loader,10,0.1,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN2 (GELU)')
  print(f'Loss: MultiMargin')
  print(f'LR: 0.1')
  print(f'Accuracy: {accuracy}%')
def train_run_test_ELU_hinge_1():
  train_loader = download_training_dataset(100)
  test_loader = download_testing_dataset(100)
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  model = CNN3().to(device)
  train_model_hinge(model,train_loader,10,0.1,device)
  accuracy = test_model(model,test_loader,device)
  print(f'Model: CNN3 (ELU)')
  print(f'Loss: MultiMargin')
  print(f'LR: 0.1')
  print(f'Accuracy: {accuracy}%')

train_run_test_base()
train_run_test_base_hinge()
train_run_test_base_1()
train_run_test_base_hinge_1()

train_run_test_GELU()
train_run_test_GELU_hinge()
train_run_test_GELU_1()
train_run_test_GELU_hinge_1()

train_run_test_ELU()
train_run_test_ELU_hinge()
train_run_test_ELU_1()
train_run_test_ELU_hinge_1()

